# Generated by Django 3.2.7 on 2023-04-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tactic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tactic_group', models.CharField(choices=[('UM', '用户管理类'), ('OG', '对象类'), ('C', '通信类'), ('AC', '访问控制类')], max_length=2, verbose_name='策略组')),
                ('tactic_name', models.CharField(max_length=50, verbose_name='策略名称')),
                ('risk_level', models.CharField(choices=[('L', '低级'), ('M', '中级')], max_length=2, verbose_name='风险等级')),
                ('tactic_remarks', models.CharField(max_length=100, verbose_name='策略备注')),
                ('risk_description', models.CharField(max_length=200, verbose_name='策略风险描述')),
                ('edit_suggestion', models.CharField(max_length=100, verbose_name='修改建议')),
            ],
            options={
                'verbose_name': '策略',
                'verbose_name_plural': '策略',
            },
        ),
        migrations.CreateModel(
            name='TacticRemarks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tactic_group', models.CharField(choices=[('UM', '用户管理类'), ('OG', '对象类'), ('C', '通信类'), ('AC', '访问控制类')], max_length=2, verbose_name='策略组')),
                ('remarks', models.CharField(max_length=30, verbose_name='备注')),
            ],
            options={
                'verbose_name': '策略备注',
                'verbose_name_plural': '策略备注',
            },
        ),
    ]
