# Generated by Django 3.2.7 on 2023-04-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('request_method', models.CharField(max_length=10)),
                ('request_url', models.CharField(max_length=200)),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
