# Generated by Django 3.2.7 on 2023-04-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='is_logged_in_first_time',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
