# Generated by Django 3.2.7 on 2023-05-10 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sort_id', models.IntegerField()),
                ('address', models.CharField(max_length=20)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('remark', models.CharField(blank=True, default='无', max_length=50, null=True)),
            ],
        ),
    ]
