# Generated by Django 3.2.7 on 2023-04-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_name', models.CharField(max_length=20)),
                ('node_ip', models.CharField(max_length=20)),
                ('node_status', models.CharField(choices=[('online', '在线'), ('offline', '离线')], max_length=10)),
                ('last_checked', models.DateTimeField()),
                ('remark', models.CharField(max_length=20)),
            ],
        ),
    ]
